rails/associations/private-events/config/routes.rb
Rails.application.routes.draw do

  # get 'sessions/new'

  # get 'sessions/destroy'

  root 'static_pages#home'
  # delete '/signout', to: 'user#destroy'
  resources :users, only: [:new, :create, :show]
  resources :events, only: [:new, :create, :show, :index]
  resources :sessions, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

rails/associations/private-events/app/models/event.rb
class Event < ApplicationRecord
  has_many :invitations, foreign_key: :attended_event_id # referes to invitations table
  has_many :attendees, through: :invitations, source: :attendee # refers to users table through invitations table, ('source' seems optional)
  belongs_to :creator, class_name: "User" # refers to users table directly
  scope :all_upcoming_events, -> { where("date > ?", Time.now) } # scope, lets use 'all_upcoming_events' method
  scope :all_past_events, -> { where("date < ?", Time.now) } # scope, lets use 'all_past_events' method

  ########## class methods from below moved to being scopes ##########
  # def self.all_upcoming_events
  #   Event.where("date > ?", Time.now)
  # end

  # def self.all_past_events
  #   Event.where("date < ?", Time.now)
  # end

end

rails/associations/private-events/app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :attendee, class_name: "User" # join tables
  belongs_to :attended_event, class_name: "Event" # join tables
end

rails/associations/private-events/app/models/user.rb
class User < ApplicationRecord
  # has_many :events
  has_many :invitations, foreign_key: :attendee_id # refers to invitations table
  has_many :attended_events, through: :invitations, source: :attended_event # refers to events table through invitations, ('source' seems optional)
  has_many :created_events, foreign_key: :creator_id, class_name: "Event" #refers to events table directly

  def upcoming_events
    # puts "UPCOMING EVENTS"
    attended_events.select { |e| e.date.to_i > Time.now.to_i }
  end

  def previous_events
    attended_events.select { |e| e.date.to_i < Time.now.to_i }
  end

end

rails/associations/private-events/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # include UsersHelper
  include SessionsHelper
end

rails/associations/private-events/app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @all_upcoming_events = Event.all_upcoming_events
    @all_past_events = Event.all_past_events
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @user = current_user
    @event = @user.created_events.build(event_params)
    # @event.place = Faker::University.name
    # @event.date = params[:date]
    @event.save
    flash[:success] = "Event has been succesfully saved"
    redirect_to events_path
  end

  private
    def event_params
      params.require(:event).permit(:name, :description, :date)
    end
end

rails/associations/private-events/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_name(params[:session][:name])
    if @user
      session[:id] = @user.id
      session[:name] = @user.name
      flash[:success] = "You have been succesfully signed in as #{@user.name}"
      redirect_to @user
    else
      flash[:warning] = "There is no such user"
      render 'new'
    end
  end

  def destroy
    session.delete(:name)
    session.delete(:id)
    @current_user = nil
    flash[:success] = "You have been signed out succesfully"
    redirect_to root_url
  end
end

rails/associations/private-events/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

rails/associations/private-events/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    # (note to me in future) refactor to use helper method
    if session[:name].nil?
      @user = User.new
    else
      @user = User.find(session[:id])
      flash[:info] = "You are already signed in"
      redirect_to @user
    end
  end

  def create
    @user = User.new(user_params)
    @user.save
    session[:name] = @user.name
    session[:id] = @user.id
    # cookies[:name] = @user.name
    # cookies[:id] = @user.id
    redirect_to @user
  end

  def show
    @user = User.find(params[:id])
    @created_events = @user.created_events
    @upcoming_events = current_user.upcoming_events
    @previous_events = current_user.previous_events
  end

  def destroy
    session.delete(:id)
    @current_user = nil
  end

  private
    def user_params
      params.require(:user).permit(:name)
    end

end

rails/associations/private-events/app/helpers/events_helper.rb
module EventsHelper
end

rails/associations/private-events/app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user?
    !session[:name].nil?
  end

  def current_user
    if (user_id = session[:id])
      @current_user ||= User.find(user_id)
    end
  end

end

rails/associations/private-events/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

rails/associations/private-events/app/helpers/users_helper.rb
module UsersHelper

  ###### moved to SessinosHelper
  # def current_user?
  #   !session[:user_name].nil?
  # end

  # def current_user
  #   # @current_user = User.find(session[:id])
  #   if (user_id = session[:id])
  #     @current_user ||= User.find(user_id)
  #   end
  # end

end

rails/associations/private-events/app/views/events/index.html.erb
<div class="container">
  <h3>All upcoming Events</h3>
  <table class="table">
    <thead>
      <tr>
        <th>Event name</th>
        <th>Place</th>
        <th>Event Date</th>
        <th>Event Creator</th>
        <th></th>
      </tr>
    </thead>
    <tbody>

      <tr><% @all_upcoming_events.each do |e| %></tr>
        <td><%= e.name %></td>
        <td><%= e.place %></td>
        <td><%= e.date %></td>
        <td><%= e.creator.name %></td>
        <td><%= link_to "Show details", event_path(e), class: "btn btn-primary" %></td>
      <% end %>

    </tbody>
  </table>

  <h3>All past events</h3>
  <table class="table">
    <thead>
      <tr>
        <th>Event name</th>
        <th>Place</th>
        <th>Event Date</th>
        <th>Event Creator</th>
      </tr>
    </thead>
    <tbody>

      <tr><% @all_past_events.each do |e| %></tr>
        <td><%= e.name %></td>
        <td><%= e.place %></td>
        <td><%= e.date %></td>
        <td><%= e.creator.name %></td>
      <% end %>

    </tbody>
  </table>
</div>

rails/associations/private-events/app/views/events/new.html.erb
<%= form_for @event do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :date %>
  <%= f.datetime_select :date %>

  <%= f.submit "create event!" %>
<% end %>

rails/associations/private-events/app/views/events/show.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Event name</th>
      <th>Event Place</th>
      <th>Event Date</th>
      <th>Event Creator</th>
    </tr>
  </thead>
  <tbody>
    <td><%= @event.name %></td>
    <td><%= @event.place %></td>
    <td><%= @event.date %></td>
    <td><%= @event.creator.name %></td>
  </tbody>
</table>
<h3>Event description</h3>
<p><%= @event.description %></p>

rails/associations/private-events/app/views/users/create.html.erb
<!-- not needed -->
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

rails/associations/private-events/app/views/users/new.html.erb
<h2>Sign up!</h2>

<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit "Sign in now!" %>
<% end %>

rails/associations/private-events/app/views/users/show.html.erb
<h3>User profile page: <%= @user.name if @user %></h3>

<div class="container">
  <p>Created events: </p>
  <table class="table">
    <thead>
      <tr>
        <th>Event name</th>
        <th>Place</th>
        <th>Event Date</th>
        <th>Event Creator</th>
        <th>Attendees</th>
      </tr>
    </thead>
    <tbody>

        <tr><% @created_events.each do |e| %></tr>
          <td><%= e.name %></td>
          <td><%= e.place %></td>
          <td><%= e.date %></td>
          <td><%= e.creator.name %></td>
          <td>
            <% e.attendees.each do |a| %>
              <%= a.name %>,
            <% end %>
          </td>
        <% end %>

    </tbody>
  </table>

  <p>Upcoming events: </p>
    <table class="table">
      <thead>
        <tr>
          <th>Event name</th>
          <th>Place</th>
          <th>Event Date</th>
          <th>Event Creator</th>
          <th>Event Attendees</th>
        </tr>
      </thead>
      <tbody>

          <tr><% @upcoming_events.each do |e| %></tr>
            <td><%= e.name %></td>
            <td><%= e.place %></td>
            <td><%= e.date %></td>
            <td><%= e.creator.name %></td>
            <td>
              <% e.attendees.each do |a| %>
                <%= a.name %>,
              <% end %>
            </td>
          <% end %>

      </tbody>
    </table>

  <p>Previous events: </p>
    <table class="table">
      <thead>
        <tr>
          <th>Event name</th>
          <th>Place</th>
          <th>Event Date</th>
          <th>Event Creator</th>
          <th>Event Attendees</th>
        </tr>
      </thead>
      <tbody>

          <tr><% @previous_events.each do |e| %></tr>
            <td><%= e.name %></td>
            <td><%= e.place %></td>
            <td><%= e.date %></td>
            <td><%= e.creator.name %></td>
            <td>
              <% e.attendees.each do |a| %>
                <%= a.name %>,
              <% end %>
            </td>
          <% end %>

      </tbody>
    </table>

</div>