rails/sample_app/config/routes.rb
Rails.application.routes.draw do

  # get 'sessions/new'

  # syntax error, unexpected => root to: => "static_pages#home" ^
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'# , as: 'pomidor'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create' # turned of by listing 8.2
                                     # turn on by exercise 10.1.1.2
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  # get 'static_pages/help'
  # get 'static_pages/about'
  # get 'static_pages/contact'

end

rails/sample_app/app/models/user.rb
class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed # override ungramatical 'followeds' with 'following' using `source` option. This is because Rails can't derive by itself the column name from 'following' method, so we need to provide `source` option for it to know to look for `followed_id` column in relationships table
  has_many :followers, through: :passive_relationships, source: :follower # `source` option can be omitted because rails can singularize `followers` by itself and look for follower_id column in relationships table
  attr_accessor :remember_token, :activation_token, :reset_token # virtual (not in db) attributes used below
  before_save   :downcase_email
  before_create :create_activation_digest
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false}
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  class << self # everything in this scope is a class method and is (almost)equivalent to: `def User.digest` & `def User.new_token` OR `def self.digest` & `def self.new_token` (without defining `class << self` scope)

    # digest password used in test/fixtures/users.yml
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # returns a random token, 22 alphanums(random case)
    def new_token
      SecureRandom.urlsafe_base64
    end

  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    # remember_digest is the same as self.remember_digest above (?)
    # remember_token is only a local variable. It refers to remember_token from attr_accessor so its common to name this method attribute the same
    digest = self.send("#{attribute}_digest") # may be without `self` since in User model
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def activate
    # update_attribute(:activated, true)
    # update_attribute(:activated_at, Time.zone.now)
    update_columns(activated: true, activated_at: Time.zone.now) # exercise 11.3.3.1
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def create_reset_digest
    self.reset_token = User.new_token
    # update_attribute(:reset_digest, User.digest(reset_token))
    # update_attribute(:reset_sent_at, Time.zone.now)
    update_columns(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now) # exercise 12.3.3.1
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
    # i.e
    # reset_sent_at == 15:00
    # Time.now == 16:00
    # 2.hours.ago => max 14:00
    # 15:00 > 14:00
    # returns false (not expired)
    #
    # reset_sent_at == 15:00
    # Time.now == 18:00
    # 2.hours.ago => max 16:00
    # 15:00 < 16:00
    # returns true (expired)
  end

  def feed
    # `User.first.following_ids` => shorthand of `User.first.following.map(&:id)`

    # 1ST VERSION
    # good when only one record needs to be pulled
    # Micropost.where("user_id IN (?) OR user_id = ?", following_ids, id) # This is good when we are pulling only one record

    # 2ND VERSION
    # good when more than record needs to be pulled
    # Micropost.where("user_id IN (:following_ids) OR user_id = :user_id", following_ids: following_ids, user_id: id)

    # 3RD VERSION
    # best for scaling horizontally
    following_ids = "SELECT followed_id FROM relationships WHERE follower_id = :user_id"
    Micropost.where("user_id IN (#{following_ids}) OR user_id = :user_id", user_id: id) # more efficent than the query below

    # For details refer to section 14.3.3 Subselects of the railstutorial book

    # ex 14.3.2.1 Posts from self test will fail
    # ex 14.3.2.2 Post from followed user will fail
    # Micropost.all # exercise 14.3.2.3 make third test block fail
  end

  def follow(other_user)
    following << other_user # as in console `user.following << other_user`
  end

  def unfollow(other_user)
    following.delete(other_user) # as in console `user.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user) # as in console `user.include?(other_user)
  end

  private

    def downcase_email
      # self.email = email.downcase
      self.email.downcase! # exercise 11.1.2.3
    end

    def create_activation_digest
      self.activation_token = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

# /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

rails/sample_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :following, :followers]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    @users = User.where(activated: true).paginate(page: params[:page], per_page: 30)  # exercise 11.3.3.2
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
    redirect_to root_url and return unless @user.activated? # exercise 11.3.3.2
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email # code moved to User model
      flash[:success] = "Please check your email to activate your account"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    # @user = User.find(params[:id]) # turned off by correct_user method
  end

  def update
    # @user = User.find(params[:id]) # turned off by correct_user method
    if @user.update_attributes(user_params)
      flash[:success] = "Changes has been saved"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed"
    redirect_to users_path
  end

  def following
    @title = "Following" # yielded by view
    @user = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers" # yielded by view
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    # before filters

    # logged_in_user has been moved to ApplicationController
    # exercise 13.3.1.1
    # leaving 'logged_id_user' here will override method defined in application controller and changes made there wont affect UsersController
    # It is also code repetition

    # confirms the corrent user
    def correct_user
      @user = User.find(params[:id])
      redirect_to root_url unless current_user?(@user)
    end

    # confirms the admin user
    def admin_user
      redirect_to root_url unless current_user.admin?
    end

end

rails/sample_app/app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

rails/sample_app/app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div> <!-- will send followed_id param with the value of id of the previewed user (id param of current url) to RelationshipController#follow action -->
  <%= f.submit "Follow", class: 'btn btn-primary' %>
<% end %>

rails/sample_app/app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
  </div>
<% end %>

rails/sample_app/app/views/users/_form.html.erb
<%= form_for @user, url: yield(:url) do |f| %> <!-- exercise 10.1.1.2 -->
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control'  %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control'  %>

  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation, class: 'form-control'  %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>

<% end %>

rails/sample_app/app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id), html: {method: :delete}, remote: true) do |f| %> <!-- will send previewed user id to params to use it in RelationshipsController#unfollow action -->
  <%= f.submit "Unfollow", class: 'btn' %>
<% end %>

rails/sample_app/app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to 'delete', user, method: :delete, data: { confirm: 'Are you sure?'} %>
  <% end %>
</li>

rails/sample_app/app/views/users/edit.html.erb
<!-- passing variables -->
<%= provide :title, 'Edit' %>
<%= provide :button_text, 'Save changes' %>
<%= provide :url, user_path %> <!-- exercise 10.1.1.2 -->

<h1>Update your profile</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <!-- url: signup_path added for excluded from resources :users, the post('/signup', to: users#create) -->
  <%= render 'form' %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank" rel="noopener">Change</a>
    </div>
  </div>
</div>

rails/sample_app/app/views/users/index.html.erb
<%= provide :title, 'All users' %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">

  <%= render @users %>

</ul>

<%= will_paginate %>

rails/sample_app/app/views/users/new.html.erb
<!-- passing variables -->
<%= provide :title, 'Sign up' %>
<%= provide :button_text, 'Create my account' %>
<%= provide :url, signup_path %> <!-- exercise 10.1.1.2 -->

<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
  <!-- url: signup_path added for excluded from resources :users, the post('/signup', to: users#create) -->
    <%= render 'form' %>
  </div>
</div>

rails/sample_app/app/views/users/show.html.erb
<%= provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
  </aside>
    <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>

</div>

rails/sample_app/app/views/users/show_follow.html.erb
 <!-- This view corresponds to UsersController#follow/unfollow actions, therefore all instance variables defined there are available here -->
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Microposts:</b> <%= @user.microposts.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %> <!-- ex. 14.2.3.2 Lines 16 and 26 may be removed to fail the test -->
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %> <!-- ex. 14.2.3.2 Lines 16 and 26 may be removed to fail the test -->
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>