rails/sample_app/config/routes.rb
Rails.application.routes.draw do

  # get 'sessions/new'

  # syntax error, unexpected => root to: => "static_pages#home" ^
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'# , as: 'pomidor'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create' # turned of by listing 8.2
                                     # turn on by exercise 10.1.1.2
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  # get 'static_pages/help'
  # get 'static_pages/about'
  # get 'static_pages/contact'

end

rails/sample_app/app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

rails/sample_app/app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
<!--     Here Rails knows to call the micropost partial because each element of @feed_items has class Micropost. This causes Rails to look for a partial with the corresponding name in the views directory of the given resource:

app/views/microposts/_micropost.html.erb -->

  </ol>
  <%= will_paginate @feed_items %>
<% end %>

rails/sample_app/app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
  <span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var sizeInMegabytes = this.files[0].size/1024/1024;
    if (sizeInMegabytes > 5) {
      alert('Maximum file size is 5MB. Please choose smaller file');
    }
  });
</script>

rails/sample_app/app/views/shared/_stats.html.erb
<% @user ||= current_user %> <!-- @user for 'show' page and 'current_user' for home page -->
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %> <!-- calculate directly in database for efficiency -->
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %> <!-- calculate directly in database for efficiency -->
    </strong>
    followers
  </a>
</div>

rails/sample_app/app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>